FROM geerlingguy/php-apache:latest
#RUN rm /var/www/html/index.html

COPY uploads.ini /usr/local/etc/php/conf.d/

RUN echo "file_uploads = On\n" \
         "memory_limit = 500M\n" \
         "upload_max_filesize = 500M\n" \
         "post_max_size = 500M\n" \
         "max_execution_time = 600\n" \
         > /usr/local/etc/php/conf.d/uploads.ini



COPY . /var/www/html/.

RUN chmod -R 777 /var/www/html
RUN chmod -R 777 /var/www/html/cat

COPY ./ports.conf /etc/apache2/ports.conf
COPY ./apache.conf /etc/apache2/site-enabled/000-default.conf