#FROM geerlingguy/php-apache:latest
FROM php:8.0-apache


#RUN rm /var/www/html/index.html
COPY . /var/www/html/.

COPY ./ports.conf /etc/apache2/ports.conf
COPY ./apache.conf /etc/apache2/site-enabled/000-default.conf